name: Run Unit Tests
on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string
      test-project:
        required: true
        type: string
    secrets:
      MYGETTOKEN:
        required: true
jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x
      - name: Add MyGet repository
        run: dotnet nuget add source https://www.myget.org/F/fireflybackbone/api/v3/index.json -n firefly-backbone -u fireflybackbone --store-password-in-clear-text -p "$MYGETTOKEN"
        env:
          MYGETTOKEN: ${{secrets.MYGETTOKEN}}
      - uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget
      - name: Install Dependencies
        run: dotnet restore ${{ inputs.test-project }}
      - name: Run Tests
        run: dotnet test --logger trx --results-directory results-${{ inputs.project-name }} ${{ inputs.test-project }}
      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results-${{ inputs.project-name }}
          path: results-${{ inputs.project-name }}
        if: ${{ always() }}
