name: Publish a NuGet package to MyGet
on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      version:
        required: true
        type: string
    secrets:
      MYGETTOKEN:
        required: true
jobs:
  publish:
    runs-on: ubuntu-latest-lr
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x
      - name: Add MyGet repository
        run: dotnet nuget add source https://www.myget.org/F/fireflybackbone/api/v3/index.json -n firefly-backbone -u fireflybackbone --store-password-in-clear-text -p "$MYGETTOKEN"
        env:
          MYGETTOKEN: ${{secrets.MYGETTOKEN}}
      - uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget
      - name: Build the project
        run: dotnet build --configuration Release ${{inputs.project}}
      - name: Create the package
        run: dotnet pack --no-build --configuration Release ${{inputs.project}} /p:Version=${{inputs.version}}
      - name: Publish to MyGet
        run: dotnet nuget push ${{inputs.project}}/bin/Release/*.nupkg --source https://www.myget.org/F/fireflybackbone/api/v2/package -k "$MYGETTOKEN"
        env:
          MYGETTOKEN: ${{secrets.MYGETTOKEN}}

